### ISSUE TITLE
teams/players incorrectly parsed

### ISSUE THREAD

**Issue by sixty** [ascendedguard/sc2replay-csharp#10]
This seems to be the case with some random replays. At first I was under the impression that its related to the new patch, but it seems to happen also with 1.3.3 replays. Players are wrongly reported to all being on Team 0 in some cases. I attached a replay where this happens:

http://replayfu.com/r/Pz9Zvf

The replay and teams are parsed correctly by the other parsers out there.

**Comment by ascendedguard** [comment]
It seems the team returned by the player details structure is unreliable, I confirmed that this is true in your replay and some other parsers do ignore this field as unreliable. It seems to place to grab this is when parsing the replay.attributes.events, so might require some work to get the right values here.

**Comment by ascendedguard** [comment]
This should be fixed in the latest commit where I redid the ReplayAttributeEvents file, I rely only on this for the correct team numbers and it appears to be correct from my testing. Compile and test with your own replays to verify that it is indeed fixed, and let me know if you have any issues.
