### ISSUE TITLE
Foreign filenames cause crash

### ISSUE THREAD

**Issue by sixty** [ascendedguard/sc2replay-csharp#12]
Pretty much the same as with the previous issue where foreign text caused a crash it seems foreign filenames also cause trouble. 

Example: 탈다림 제단 - 래더 (17).SC2Replay - Unable to parse

The same file parses fine after renaming. This also seems to happen under a proper foreign system. I ran it on a VM running Korean Windows XP and the issue still remains, so it is probably not related to English OS trying to parse foreign files.

**Comment by ascendedguard** [comment]
I'm worried this may be an issue with MpqLib.dll, in which case, the solution for now may be to copy the file to a local, non-korean name before opening the archive. I'll look into this more over the weekend and attempt to fix it.

**Comment by ascendedguard** [comment]
Fixed with a workaround, basically if it fails to load the first time, it'll copy the file to a temp file first. Available in the latest commit.
