### ISSUE TITLE
Double namespace "replay" in the latest version

### ISSUE THREAD

**Issue by sixty** [ascendedguard/sc2replay-csharp#13]
Since the latest version, the DLL contains the namespace "replay" twice. Once with a capital R and once without. This is not a problem when using the DLL in C#, but causes issues in VB.NET, which is not case sensitive.

**Comment by ascendedguard** [comment]
Yup, this is just a mistake, I'll try to fix it when I get a chance.

**Comment by ascendedguard** [comment]
Fixed in latest commit.
