### ISSUE TITLE
Replay parsing is broken in 1.2.0.6 and up.

### ISSUE THREAD

**Issue by ascendedguard** [ascendedguard/sc2replay-csharp#35]
Specifically, the format of replay.initdata file changed and needs to be fixed

**Comment by ascendedguard** [comment]
Seems to be fixed in 91dbb5fef45cce6259628a5d39dae4c4b83d3b5f

**Comment by evan449** [comment]
This seems unable to parse out the Gamelength.Is it because the event unable to parse the relationship？

**Comment by ascendedguard** [comment]
Yeah, the GameLength does rely on the events parsing out correctly.

There are changes needed to get HotS event parsing to work again, then the ability and unit files need to be compiled for each HotS version as well.

A lot of work involved here. I know the Python project has updated abil and unit codes, and Mischanix seems to have updated his gist for retrieving event codes for HotS here: https://gist.github.com/Mischanix/4164860

These need to be added to the sqlite database and recompiled accordingly.

I've opened another issue for this: #36
